# ----
# Site

title: Pullnfit
description: Pullnfit – это такой подход для фитнес-тренеров, когда каждый клиент занимается по индивидуальной программе.
url: https://pullnfit.ru
disqus_shortname: pullnfit
baseurl:

google_site_verification: googlea100b080d45acbbd.html
permalink: pretty
timezone: YEKT
collections:
  case_studies:
    output: false
    permalink: /case-studies/:name/
defaults:
  - scope:
      path: ""
    values:
      header_class: "short"
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# ----------
# SEO plugin

lang: en_NZ
logo: /siteicon.png
twitter:
  username: pullnfit
facebook:
  publisher: https://www.facebook.com/pullnfit
social:
  name: pullnfit
  links:
    - https://twitter.com/pullnfit
    - https://www.facebook.com/pullnfit
    - https://plus.google.com/+pullnfit
    - https://www.youtube.com/c/pullnfit
    - https://github.com/pullnfit

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
